package shakkiturnaus.Model.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import shakkiturnaus.Model.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.14 10:59:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsallistujaTest {



  // Generated by ComTest BEGIN
  /** testParse81 */
  @Test
  public void testParse81() {    // Osallistuja: 81
    Osallistuja uusi = new Osallistuja(); 
    String sepe = "1|Susi|Sepe|AnkSk|1300|sepe@susi.fi|0123456|0"; 
    uusi.parse(sepe); 
    assertEquals("From: Osallistuja line: 85", "1|Susi|Sepe|AnkSk|1300|sepe@susi.fi|0123456|0", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString101 */
  @Test
  public void testToString101() {    // Osallistuja: 101
    Osallistuja markku = new Osallistuja("Markku", "Mainio", "mara@mainio.fi", "JärvSk", "0414121212", "1500", 0); 
    assertEquals("From: Osallistuja line: 103", "1|Mainio|Markku|JärvSk|1500|mara@mainio.fi|0414121212|0", markku.toString()); 
  } // Generated by ComTest END
}