package shakkiturnaus.Model.test;
// Generated by ComTest BEGIN
import java.util.Iterator;
import java.io.IOException;
import static org.junit.Assert.*;
import org.junit.*;
import shakkiturnaus.Model.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.14 10:59:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloksetTest {



  // Generated by ComTest BEGIN
  /** testLisaa36 */
  @Test
  public void testLisaa36() {    // Tulokset: 36
    Tulokset tuloksia = new Tulokset(); 
    tuloksia.lisaa(new Tulos(1, 2)); 
    assertEquals("From: Tulokset line: 39", 1, tuloksia.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKirjoitaTulos61 
   * @throws IOException when error
   * @throws PoikkeusException when error
   */
  @Test
  public void testKirjoitaTulos61() throws IOException, PoikkeusException {    // Tulokset: 61
    Tulokset tul = new Tulokset(); 
    Tulos eka = new Tulos(); 
    eka.setPelaaja1(1); 
    eka.setPelaaja2(2); 
    tul.lisaa(eka); 
    tul.kirjoitaTulos(); 
    Iterator<Tulos> it = tul.iterator(); 
    assertEquals("From: Tulokset line: 72", eka.toString(), it.next().toString()); 
    assertEquals("From: Tulokset line: 73", false, it.hasNext()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTied96 */
  @Test
  public void testLueTied96() {    // Tulokset: 96
    Tulokset tul = new Tulokset(); 
    tul.lueTied(); 
    assertEquals("From: Tulokset line: 99", 1, tul.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskePelit125 */
  @Test
  public void testLaskePelit125() {    // Tulokset: 125
    Tulokset games = new Tulokset(); 
    Tulos game = new Tulos(); 
    game.setPelaaja1(1); 
    game.setPelaaja2(2); 
    games.lisaa(game); 
    Tulos game2 = new Tulos(); 
    game2.setPelaaja1(1); 
    game2.setPelaaja2(3); 
    games.lisaa(game2); 
    assertEquals("From: Tulokset line: 137", 2, games.laskePelit(1)); 
    assertEquals("From: Tulokset line: 138", 1, games.laskePelit(3)); 
    assertEquals("From: Tulokset line: 139", 0, games.laskePelit(4)); 
  } // Generated by ComTest END
}