package shakkiturnaus.Model.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import shakkiturnaus.Model.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.14 10:59:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TulosTest {



  // Generated by ComTest BEGIN
  /** testParse67 */
  @Test
  public void testParse67() {    // Tulos: 67
    String t = "2|1|3|1|2021-05-14"; 
    Tulos t1 = new Tulos(); 
    t1.parse(t); 
    assertEquals("From: Tulos line: 71", "2|1|3|1|2021-05-14", t1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString87 */
  @Test
  public void testToString87() {    // Tulos: 87
    Tulos t = new Tulos(1, 3); 
    Tulos t2 = new Tulos(3, 1); 
    assertEquals("From: Tulos line: 90", "2|1|3|1|2021-05-14", t.toString());
    assertEquals("From: Tulos line: 91", "3|3|1|3|2021-05-14", t2.toString());
  } // Generated by ComTest END
}